Disable client-side anti-exploit by default, even for old loaders
Sceleratis/Adonis pull request #1205
Opened 2023-08-22 13:11 UTC by alau740

Resolves #1204 

This adds a new setting, `settings.AllowClientAntiExploit` which is disabled by default, this new setting must also be enabled in order to use `settings.Detection` as well as the rest of the client side anti exploit options. This will also disable it for existing loaders

This pr also sets `settings.Detection` to `false` by default

This is due to an increase in the number of false positives and problems with this system, especially with the addition of byfron to the win32 client

2023-08-22 13:47 UTC, WalkerOfBacon approved these changes

2023-08-23 14:17 UTC, ccuser44 requested changes
It's not true that addition of byfron has caused more "false" detections. It's impossible for that to happen.

When byfron was added exploiters switched to low quality exploits (like celery) which are detectable.
That is the reason for added detections, they are *valid detections* (unless it results from a Roblox updated feature, most dont)

This can be proven by the increased posts in exploiter forums requesting for "Adonis bypasses".

2023-08-23 20:02 UTC, moo1210 approved these changes
If someone wants an actively maintained client-side anti-cheat (you probably don't though, this is a great example of _why_), you should get this outside of Adonis. or through a plugin. Adonis is an admin system, not an anti-cheat.

2023-09-16 12:09 UTC, LiveFireExercise commented
Hmm, I wonder

2023-09-16 14:42 UTC, alau740 commented
also i think byfron has been added to the ms store client so

2023-09-16 15:18 UTC, LiveFireExercise commented
yea lol

2023-09-16 15:20 UTC, LiveFireExercise commented
Ok so after reviewing the code I don't see anything that would cause it to break. But I am gonna test it to make sure

2023-10-24 04:29 UTC, moo1210 commented
lets just merge this so you don't join studio to get crashed because your "exploiting" for using a deprecated function with a devforum link

2023-10-24 08:40 UTC, moo1210 commented
then how does it happen on the latest nightly and stable..?

2023-10-24 10:53 UTC, LiveFireExercise commented
"lets just merge this"
"in classic adonis function the pull request doesnt work"
Wow.

2023-10-24 10:59 UTC, moo1210 commented
that was in reference to whatever ccuser was talking about, this works fine afaik. also it's literally just adding a setting lol

2023-10-24 11:02 UTC, moo1210 commented
`:: Adonis :: ANTI-EXPLOIT: moo1210 crash Exploit detected; GetCollisionGroups is deprecated, please use GetRegisteredCollisionGroups instead. More info: https://devforum.roblox.com/t/updates-to-collision-groups/1990215` (spammed repeatedly to the point of not even saving to the log file)

![image](https://github.com/Epix-Incorporated/Adonis/assets/27241938/3a5e7d24-1344-4e58-b619-eb2e666fc6e3)

I can confirm this is stopping all the exploiters, I'm sure the soon-to-be-shutdown v3rm forum would agree.

2023-10-24 11:11 UTC, LiveFireExercise commented
Yes.

2023-10-24 12:59 UTC, merged