system small message
Sceleratis/Adonis pull request #223
Opened 2021-01-04 09:21 UTC by pbstFusion

Changed the title to the thing in settings

2021-01-04 14:47 UTC, Awesomewebm requested changes
The Name of the Command Array `Notify = {` cannot have the same name, or they will override each other and mess it up.

2021-01-04 18:28 UTC, pbstFusion commented
Riight

2021-01-04 18:33 UTC, pbstFusion commented on MainModule/Server/Core/Commands.lua
> +		Notify = {
Change title to SystemNotify

2021-01-05 09:58 UTC, pbstFusion commented
I CANNOT figure out how too change it

2021-01-05 09:58 UTC, closed without merging