Add region information in :serverinfo
Sceleratis/Adonis pull request #411
Opened 2021-07-10 04:37 UTC by LolloDev5123

![Roblox 10_07_2021 05_48_20](https://user-images.githubusercontent.com/26120324/125151758-c42b5080-e148-11eb-823b-ad990aa213a2.png) <-- got inspired by arsenal kiddies
![random stuff i make for adonis - Roblox Studio 10_07_2021 06_35_05](https://user-images.githubusercontent.com/26120324/125151788-00f74780-e149-11eb-83a1-d8144c9f66b4.png)

**-- IMPORTANT --**
I do not know if it would be ethical to include an IP Address, it is very possible. I have fear this may be exploitable and make it easier for skids to DDOS servers (already possible)
Second issue: When in studio, the ip could reveal yours to unwanted people, so I don't know if it is good to add one and if we do, we might censor it in studio.

Please note that there may be some bugs, such as error handling, checking if HTTP is on, but on the other hand, this would be a pretty good addition to :serverinfo or :serverdetails.

2021-07-10 04:37 UTC, LolloDev5123 commented
do note the region and things are approximations so yeah while i do live in italy im not even in apulia or veglie lol

2021-07-10 04:49 UTC, joritochip requested changes

2021-07-10 04:49 UTC, joritochip commented on MainModule/Server/Commands/Moderators.lua
> +				local serii = getServerInternetInfo()
```suggestion
				local s, r = pcall(service.HttpService.GetAsync, service.HttpService, "http://ip-api.com/json")
				if s then
					r = service.HttpService:JSONDecode(r)
				end
				local serverInfo = s and {
					country = r.country 
					city = r.city 
					region = r.region 
					zipcode = r.zipcode 
					timezone = r.timezone 
				} or nil
```

2021-07-10 04:49 UTC, joritochip commented on MainModule/Server/Commands/Moderators.lua
> +					ServerInternetInfo = serii;
```suggestion
					ServerInternetInfo = serverInfo;
```

2021-07-10 04:49 UTC, joritochip commented on MainModule/Client/UI/Default/ServerDetails.lua
> +
```suggestion
		if data.ServerInternetInfo then
			--Server Internet Info
			local serii = data.ServerInternetInfo
			addOverviewEntry("Timezone:", serii.timezone or "[Error]")
			addOverviewEntry("Country:", serii.country or "[Error]")
			addOverviewEntry("Region:", serii.region or "[Error]")
			addOverviewEntry("City:", serii.city or "[Error]")
			addOverviewEntry("Zipcode:", serii.zipcode or "[Error]")
		end
```

2021-07-10 05:05 UTC, joritochip requested changes
oops

2021-07-10 05:05 UTC, joritochip commented on MainModule/Server/Commands/Moderators.lua
> +					timezone = r.timezone
```suggestion
					country = r.country,
					city = r.city,
					region = r.region,
					zipcode = r.zip,
					timezone = r.timezone
```

2021-07-10 13:50 UTC, P3tray commented
Sir just add an :IsStudio and if true remove the location info from the list. It also means you can include the IP then.

For some of us leaking our city is quite bad considering their size in rural countries. My home location doesn't exactly have millions living there.

IsStudio would fix that.

2021-07-10 14:47 UTC, Kw6m commented
I don't think you can get the players IP... Only the servers IP. If I am wrong do point it out to me please. But if the IP is available to the server. Don't display it. Region sure. But IP? The neanderthal's that would be interested in peoples IP's wouldnt be using it for good.

2021-07-10 15:16 UTC, P3tray commented
> I don't think you can get the players IP... Only the servers IP. If I am wrong do point it out to me please. But if the IP is available to the server. Don't display it. Region sure. But IP? The neanderthal's that would be interested in peoples IP's wouldnt be using it for good.
> 
> But yes showing the servers IP does no harm. Showing the servers location _also_ does no harm

This is the IP for the server. If this is a studio test server than it'll be ran from your pc, and therefore your IP.

Not good for taking screenshots or working in teamcreate "anonymously".

Hence my suggestion.

And technically speaking you can't take IP's from clients.

2021-07-10 16:38 UTC, Sceleratis commented
I see no harm in showing the server's IP.

2021-07-10 16:43 UTC, LolloDev5123 commented
It could lead to DDOSING, but hey, an exploiter with a potent enough exploit could already get the IP, so, I can show the IP and coordinates? The city is always an approximation, the only things that are right are the region, country, and timezone, I would personally blur out city, IP, and region when someone is in studio, as you could give too much details when screensharing a playtest.

2021-07-10 16:57 UTC, coasterteam commented
> I see no harm in showing the server's IP.

As long as it's only shown to people with elevated permissions

2021-07-10 17:04 UTC, Sceleratis commented
> 
> 
> It could lead to DDOSING, but hey, an exploiter with a potent enough exploit could already get the IP, so, I can show the IP and coordinates? The city is always an approximation, the only things that are right are the region, country, and timezone, I would personally blur out city, IP, and region when someone is in studio, as you could give too much details when screensharing a playtest.

Um. You can already see the IP of the server you're connected to... no exploits required. So....

2021-07-10 19:41 UTC, joritochip commented
> > It could lead to DDOSING, but hey, an exploiter with a potent enough exploit could already get the IP, so, I can show the IP and coordinates? The city is always an approximation, the only things that are right are the region, country, and timezone, I would personally blur out city, IP, and region when someone is in studio, as you could give too much details when screensharing a playtest.
> 
> Um. You can already see the IP of the server you're connected to... no exploits required. So....
> 
> Also as to the studio thing I feel like that's kinda niche and would be their own fault, but if it really bothers you, you can just check if they're in studio or not and then return something like "N/A" or "Studio"

It is also possible to get the IP of any given server without even connecting to it through the API, so I would agree in saying that having the IP there is not that big of an issue.

2021-07-11 00:27 UTC, LolloDev5123 commented
Alright, I guess this is ready to be pushed? Senstive data such as Region, IP, City, and ZIP Code are not shown when play testing.

2021-07-12 05:21 UTC, LolloDev5123 commented
Check this stuff for the last time as this is good to be merged I guess

2021-07-15 13:36 UTC, merged