Bri'ish speeling chanj
Sceleratis/Adonis pull request #705
Opened 2022-02-21 16:42 UTC by pbstFusion

I have are a very particular set of skills. Skills I have acquired over a very long career. Skills that make me a nightmare for people like you. If you merge the request, that'll be the end of it. I will not look for you, I will not pursue you, but if you don't, I will look for you, I will find you and I will forcibly teach you how to install Fortnite in binary.

2022-02-21 16:45 UTC, pbstFusion commented
I can already feel the angry comments,

2022-02-21 17:05 UTC, GalacticInspired requested changes
I request changes.

2022-02-21 17:09 UTC, pbstFusion commented
> You're all idiots, discussing over the arrangement of a single letter, over american and british english. American english is clearly superior. I don't care if you come from Worse Britain or Kan'ah'da.

If it doesn't matter, why are you arguing about it? :)

2022-02-21 17:11 UTC, GalacticInspired requested changes

2022-02-21 17:11 UTC, GalacticInspired commented on MainModule/Client/UI/Default/CommsCenter.lua
> +			if table.find(reCountries, service.LocalizationService:GetCountryRegionForPlayerAsync(service.Players.LocalPlayer)) => 1 then
Disgusting

2022-02-21 17:11 UTC, Awesomewebm commented
This is one of the most unnecessary PRs ever :D

2022-02-21 17:11 UTC, pbstFusion commented on MainModule/Client/UI/Default/CommsCenter.lua
> +			if table.find(reCountries, service.LocalizationService:GetCountryRegionForPlayerAsync(service.Players.LocalPlayer)) => 1 then
didn't ask

2022-02-21 17:21 UTC, pbstFusion commented
> This is one of the most unnecessary PRs ever :D
No, that would be the one that randomly removed the functionality in the first place

2022-02-21 17:45 UTC, joritochip approved these changes

2022-02-21 17:47 UTC, GalacticInspired commented
This is stupid

2022-02-21 17:50 UTC, pbstFusion commented
> This is stupid

You are entitled to your own opinion, even if it is false/incorrect/wrong.

2022-02-21 19:36 UTC, GalacticInspired commented
it's not useful in anyway, and it wouldn't make sense that this is the only british spelled word in whole adonis

2022-02-21 20:00 UTC, ccuser44 commented
Oi mate do you have a loisence for that?

2022-02-21 20:01 UTC, ccuser44 commented
But fr do we reslly need a single letter thing here? Lol. If so then maybe we should translate all of Adonis. If not then this is unnecessary

2022-02-21 20:03 UTC, GalacticInspired commented
it’s either all adonis or nothing

why should this command be the only thing to stand out?

2022-02-21 20:03 UTC, ccuser44 commented
also this code would even work because `table.find` can return `nil`

2022-02-21 20:05 UTC, ccuser44 commented
Wait the weirdest thing I realised is, that this command had a version before this where it chsnged it based on american english

Why was thid implemented in  the first place?

2022-02-21 20:07 UTC, GalacticInspired commented
Sceleratis wants to keep adonis AE (American English) based, so he just
changed all cent*re *to center.

2022-02-21 20:09 UTC, ccuser44 commented
> Sceleratis wants to keep adonis AE (American English) based, so he just
> changed all cent*re *to center.

Or we could just do 
`math.random(1, 2) ==2 and "Centre" or "Center"`

2022-02-21 20:10 UTC, GalacticInspired commented
Die

2022-02-23 02:52 UTC, Sceleratis commented
On a more realistic note, if we are going to do this we would need to do this via localization, not one off/one-by-one basis... otherwise we're going to have word checks everywhere adding additional overhead and code that doesn't need to be there.

2022-02-23 06:06 UTC, GalacticInspired commented
Just close this

2022-03-16 22:25 UTC, moo1210 commented
Doesn't seem so. Only see en-us in CoreScriptLocalization.

2022-03-17 16:51 UTC, LolloDev5123 commented
> Doesn't seem so. Only see en-us in CoreScriptLocalization.

pbstFusion go mine crypto to my address
`3P44apMLSALiV8yJDJdZNpmpGC1aWiowXw`

2022-03-19 19:48 UTC, GalacticInspired commented
![image](https://user-images.githubusercontent.com/73362346/159136259-dd00d430-e0c7-4a9a-bf2a-7d352263b852.png)

2022-03-19 20:19 UTC, pbstFusion commented
That is the pinnacle of satire.

2022-03-19 20:21 UTC, pbstFusion commented
Actually I have just has an infinite iq idea

2022-03-19 20:21 UTC, closed without merging