Tell other admins if the help request has already been met.
Sceleratis/Adonis pull request #753
Opened 2022-04-24 14:35 UTC by P3tray

2022-04-24 14:43 UTC, ccuser44 approved these changes

2022-04-24 14:45 UTC, ccuser44 requested changes

2022-04-24 14:45 UTC, ccuser44 commented on MainModule/Server/Commands/Players.lua
> +												Icon = "rbxassetid://7501175708";
Should be set to `Icon = server.MatIcons.Mail;`

2022-05-16 13:11 UTC, P3tray commented
This is ready to be merged now.

2022-05-16 19:35 UTC, pbstFusion commented
You're mother.

2022-05-16 20:47 UTC, merged