Add epix inc logo as icon
Sceleratis/Adonis pull request #764
Opened 2022-05-01 17:32 UTC by pbstFusion

Committing in accordance with the prophecy.

2022-05-01 17:35 UTC, joritochip requested changes

2022-05-01 17:35 UTC, joritochip commented on MainModule/Server/Shared/MatIcons.lua
> +	["Epix"] = 7681261289
Missing comma

2022-05-01 17:36 UTC, pbstFusion commented
my bad

2022-05-01 17:37 UTC, pbstFusion commented
boom fixed

2022-05-03 19:56 UTC, ccuser44 approved these changes

2022-05-04 08:14 UTC, P3tray approved these changes

2022-05-04 12:33 UTC, P3tray approved these changes

2022-05-11 17:14 UTC, merged