whoooooooshhhhhhhhhhhhhhh....
Sceleratis/Adonis pull request #790
Opened 2022-06-05 07:34 UTC by TheLegendarySpark

This is my first time contributing this year. Woohoo!! I could say that I look forward to contributing again. After a year since I began developing Essential, my custom admin system, it's been real quiet for me. I definitely imported several functions from it for performance improvements. Hope you like it! 😊 

### Additions
+ Added settings.CommandCooldowns
+ Newly improved rate limit for process
+ Added several service functions: GetProductInfo, GetGroupCreatorId, CheckAssetOwnership, CheckPassOwnership, & GetProductInfo
+ Added Admin.UpdateCooldown

### Improvements & Changes
+ Admin.DoCheck no longer requires a player object for checking gamepass ownership and group ranks
   - This change reduces the number of yields for permission checking. It's also beneficial in the event of Roblox broken and other Roblox issues
+ Reorganized the code inside Process.Command and moved the permission checks to Admin.CheckPermission

2022-06-05 18:28 UTC, P3tray commented
Welcome back.

2022-06-12 15:09 UTC, Sceleratis commented
Please do not use dumb pull titles qq

2022-06-12 15:12 UTC, Sceleratis commented on MainModule/Server/Core/Admin.lua
> +		DoHideChatCmd = function(p, message, data)
Why'd you remove the types?

2022-06-20 09:25 UTC, P3tray requested changes
@TheLegendarySpark This pull is unsuitable in it's current state. It reverts changes done by @Expertcoderz previously, namely the type safety and index variable renaming. Can you please move your code to the latest branch?

2022-06-20 21:00 UTC, merged

2022-06-20 21:01 UTC, Expertcoderz commented
Merged, now time to test if everything in this huge update works as intended.